export type TEXT_TYPO =
  | "HEADER_1"
  | "HEADER_1_B"
  | "HEADER_1_LG"
  | "HEADER_1_LG_B"
  | "HEADER_1_XL"
  | "HEADER_1_XL_B"
  | "HEADER_2"
  | "HEADER_2_B"
  | "HEADER_2_LG"
  | "HEADER_2_LG_B"
  | "HEADER_2_XL"
  | "HEADER_2_XL_B"
  | "HEADER_3"
  | "HEADER_3_B"
  | "HEADER_3_LG"
  | "HEADER_3_LG_B"
  | "HEADER_3_XL"
  | "HEADER_3_XL_B"
  | "HEADER_4"
  | "HEADER_4_B"
  | "HEADER_4_LG"
  | "HEADER_4_LG_B"
  | "HEADER_4_XL"
  | "HEADER_4_XL_B"
  | "HEADER_5"
  | "HEADER_5_B"
  | "HEADER_5_LG"
  | "HEADER_5_LG_B"
  | "HEADER_5_XL"
  | "HEADER_5_XL_B"
  | "HEADER_6"
  | "HEADER_6_B"
  | "HEADER_6_LG"
  | "HEADER_6_LG_B"
  | "HEADER_6_XL"
  | "HEADER_6_XL_B"
  | "PARAGRAPH"
  | "PARAGRAPH_B"
  | "PARAGRAPH_SM"
  | "PARAGRAPH_SM_B"
  | "PARAGRAPH_LG"
  | "PARAGRAPH_LG_B"
  | "PARAGRAPH_XL"
  | "PARAGRAPH_XL_B"
  | "TEXT"
  | "TEXT_B"
  | "TEXT_SM"
  | "TEXT_SM_B"
  | "TEXT_LG"
  | "TEXT_LG_B"
  | "CAPTION"
  | "CAPTION_B"
  | "CAPTION_SM"
  | "CAPTION_SM_B";

export const PAGE_LIST = {
  HOME: "",
  PRODUCT: "/product",
} as const;

export type TYPE_PAGE_LIST = keyof typeof PAGE_LIST;
