import { ToastProvider } from "@/component/AppToast";
import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import AuthNotification from "@/component/AuthNotification";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // tuỳ chọn
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>
        <ToastProvider>
          <Providers>
            <AuthNotification />
            {children}
          </Providers>
        </ToastProvider>
      </body>
    </html>
  );
}
