export const IMAGE_SOUCE = {
  BANNER_1_ICON_1: "/assets/images/banner_1_icon_1.png",
  BANNER_1_ICON_2: "/assets/images/banner_1_icon_2.png",
  ICON_SALE_CONTENT_1: "/assets/images/icon_sale_content_1.png",
  ICON_SALE_CONTENT_2: "/assets/images/icon_sale_content_2.png",
  BANNER_1: "/assets/images/banner_1.png",
  Home_intro_left: "/assets/images/Home_intro_left.png",
  Home_intro_right: "/assets/images/Home_intro_right.png",
  Home_intro_avatar: "/assets/images/Home_intro_avatar.jpg",
  Home_intro_food: "/assets/images/Home_intro_food.jpg",
  IMG_LOGO_APP_WHITE: "/assets/images/IMG_LOGO_APP_WHITE.png",
  IMG_LOGO_APP_BLACK: "/assets/images/IMG_LOGO_APP_BLACK.png",
  BANNER_EXPERIENCE_LEFT: "/assets/images/banner_experience_left.png",
  BANNER_EXPERIENCE_RIGHT: "/assets/images/banner_experience_right.png",
  BANNER_EXPERIENCE_FOOD: "/assets/images/banner_experience_food.png",
  BANNER_EXPERIENCE_MASTERPIECE:
    "/assets/images/banner_experience_masterpiece.png",
  BANNER_EXPERIENCE_CHEF: "/assets/images/banner_experience_chef.png",
  IMG_DEMO_PRODUCT_1: "/assets/images/IMG_DEMO_PRODUCT_1.png",
  IMG_DEMO_PRODUCT_2: "/assets/images/IMG_DEMO_PRODUCT_2.png",
  IMG_DEMO_PRODUCT_3: "/assets/images/IMG_DEMO_PRODUCT_3.png",
  IMG_DEMO_PRODUCT_4: "/assets/images/IMG_DEMO_PRODUCT_4.png",
  IMG_ABOUT_ME_1: "/assets/images/IMG_ABOUT_ME_1.jpg",
  IMG_ABOUT_ME_2: "/assets/images/IMG_ABOUT_ME_2.jpg",
  IMG_ABOUT_ME_3: "/assets/images/IMG_ABOUT_ME_3.jpg",
  IMG_ABOUT_ME_4: "/assets/images/IMG_ABOUT_ME_4.jpg",
  IMG_ABOUT_ME_5: "/assets/images/IMG_ABOUT_ME_5.jpg",
  IMG_ABOUT_ME_6: "/assets/images/IMG_ABOUT_ME_6.jpg",
  IMG_ABOUT_ME_7: "/assets/images/IMG_ABOUT_ME_7.jpg",
  IMG_ABOUT_ME_8: "/assets/images/IMG_ABOUT_ME_8.jpg",
};
