import HeaderHome from "@/component/Layout/HeaderHome";
import HeaderHomeMobile from "@/component/Layout/HeaderHomeMobile";
import { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import HomeFooter from "../(home-page)/component/Footer";
import HeaderMain from "@/component/Layout/HeaderMain";
import clsx from "clsx";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // tuỳ chọn
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <body className={robotoCondensed.className}>
          <div className="h-screen flex flex-col">
            <div>
              <HeaderMain />
              <HeaderHomeMobile />
            </div>
            <div className="flex-1">{children}</div>
            <div className="pt-20">
              <HomeFooter />
            </div>
          </div>
        </body>
      </body>
    </html>
  );
}
