import clsx from "clsx";
import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "../globals.css";

const robotoCondensed = Roboto_Condensed({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"], // tuỳ chọn
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={clsx(`min-h-screen`, robotoCondensed.className)}>
                <div className="flex flex-col h-screen">
                    <main className="flex-1">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
