import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "../globals.css";
import Tabs from "./component/Tabs";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // tuỳ chọn
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>
        <div className="bg-colorBlueLight h-screen">
          <div className="max-w-7xl mx-auto space-y-10">
            <div className="space-y-1">
              <h1 className="text-4xl font-medium">Tài Khoản Của Tôi</h1>
              <p className="text-colorGray">
                Quản lý thông tin cá nhân, địa chỉ và lịch sử mua hàng
              </p>
            </div>

            <div className="flex gap-6">
              <Tabs />
              <div className="flex-1">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
